gradle/libs.versions.toml, sample-app/build.gradle.kts, sample-app/src/main/AndroidManifest.xml, sample-app/src/main/kotlin/com/sats/dna/sample/MainActivity.kt, sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/colors/ColorsScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/icons/IconsScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/typography/TypographyScreen.kt, sample-app/src/main/res/drawable-v24/ic_launcher_foreground.xml, sample-app/src/main/res/drawable/ic_launcher_background.xml, sample-app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, sample-app/src/main/res/values/themes.xml, sats-dna/src/main/kotlin/com/sats/dna/icons/SatsIcons.kt, sats-dna/src/main/res/drawable/ic_back.xml, settings.gradle.kts
Build a sample app with some empty screens. The screens are implemented in:
- https://github.com/sats-group/sats-dna-android/pull/16
- https://github.com/sats-group/sats-dna-android/pull/17
- https://github.com/sats-group/sats-dna-android/pull/18
|   |   |
| - | - |
| ![image](https://user-images.githubusercontent.com/386122/226382440-0e26000c-934d-417d-a2ba-62d0d7910899.png) | ![image](https://user-images.githubusercontent.com/386122/226382468-986103be-3742-4262-b4c6-26b0f9e92fee.png) |
| ![image](https://user-images.githubusercontent.com/386122/226382486-6153ef26-5bf2-469d-8bcb-80fea9f8abeb.png) | ![image](https://user-images.githubusercontent.com/386122/226382534-a5c5ed35-c0a2-4b6b-9829-5f408510d854.png) |
=> NMA-4941: Sample App

sample-app/src/main/kotlin/com/sats/dna/sample/icons/IconsScreen.kt
|   |   |
| - | - |
| ![image](https://user-images.githubusercontent.com/386122/226407549-603860af-38a3-4f60-a557-3ccced74fdf6.png) | ![image](https://user-images.githubusercontent.com/386122/226407558-5cc32a6f-17fe-4231-8999-c4bff664fc95.png) |
=> NMA-4941: Sample App – Icons

sample-app/src/main/kotlin/com/sats/dna/sample/typography/TypographyScreen.kt
|   |   |
| - | - |
| ![image](https://user-images.githubusercontent.com/386122/226401762-a677bdad-3dad-406d-a1f2-0491e1db6b6a.png) | ![image](https://user-images.githubusercontent.com/386122/226401816-add5b51a-e64e-40d7-89c6-afc8fc1cd01e.png) |
=> NMA-4941: Sample App – Typography

renovate.json
Overrides https://github.com/sats-group/sats-dna-android/pull/1.
=> NMA-4946: Configure Renovate

sats-dna/src/main/kotlin/com/sats/dna/icons/SatsIcons.kt, sats-dna/src/main/res/drawable/ic_star_filled.xml, sats-dna/src/main/res/drawable/ic_star_outlined.xml
To be used in the new feedback flow
=> NMA-4963: Add star icons

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/chip/ChipsScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/chip/Chip.kt
=> NMA-5000: Create a simple SatsChip component

sample-app/src/main/kotlin/com/sats/dna/sample/colors/ColorsScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorsDark.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorsLight.kt
https://www.figma.com/file/WzKCwRY09zn4rzRVfY0YvdRt/sats-ds-styles?node-id=1-2
=> NMA-5106: Add Waiting List Text color

sample-app/src/main/kotlin/com/sats/dna/sample/icons/IconsScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/icons/SatsIcons.kt, sats-dna/src/main/res/drawable/ic_minus.xml
JIRA https://hfnswedenab.atlassian.net/browse/NMA-5133
Figma https://www.figma.com/file/07ETy9J3PsfeBH7Y0b5CHfVv/Playground?type=design&node-id=18744-256970&t=zoB8JoP2eKfTtFi6-4
=> NMA-5133 Add minus icon

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/appbar/TopAppBarScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/build.gradle.kts, sats-dna/src/main/kotlin/com/sats/dna/components/appbar/TopAppBar.kt
=> NMA-5139: Introduce SatsTopAppBar

sats-dna/src/main/res/drawable/ic_calendar.xml
Adding one that matches the other icons.
=> NMA-4935: Ditch alpha calendar icon

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/card/SatsCardScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsCard.kt
|   |   |
| - | - |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/f4731def-8c8b-48d4-86a4-94436211bfd8) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/62b0e733-e377-4f73-9b71-d1ea55c0efae) |
=> NMA-5147: Make a SatsCard composable

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/navigation/BottomNavigationScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/navigation/BottomNavigation.kt
|   |   |
| - | - |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/831bad57-2b97-4668-b3ba-c74cd13d7473) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/abadc4c9-c744-42bd-a36d-f3d78b79ac81) |
=> NMA-5154: Add bottom navigation component

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/schedule/ScheduleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/schedule/Schedule.kt, sats-dna/src/main/kotlin/com/sats/dna/components/schedule/ScheduledWorkout.kt
Adds a new `Schedule` component, which shows the upcoming workouts for a a member
| Dark | Light |
| ---- | ----- |
| ![image](https://user-images.githubusercontent.com/386122/236697743-9c4861c7-d40b-4565-84fb-de19e291483a.png) | ![image](https://user-images.githubusercontent.com/386122/236697746-54c6a54b-04a4-431e-984a-30cf525d1749.png) |
=> NMA-5155: Create Schedule component

sample-app/src/main/kotlin/com/sats/dna/sample/components/navigation/BottomNavigationScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/navigation/BottomNavigation.kt
|   |   |
| - | - |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/a3090a68-f998-41a3-a1d3-d3b63e6cee98) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/fd504487-0b72-4543-bbc0-17da2500f6d9) |
=> NMA-5162: Allow putting badges on bottom nav items

sample-app/src/main/kotlin/com/sats/dna/sample/components/buttons/ButtonsScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt
https://github.com/sats-group/sats-dna-android/assets/386122/be086262-2100-4f22-8ac5-2fa02d3ea60e
=> NMA-5172: Add icons to buttons

core-tooling/src/main/kotlin/com/sats/dna/tooling/LightDarkPreview.kt, sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/ComponentScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/RadioButtonsScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsRadioButton.kt
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/8e60e134-817c-42bb-baeb-d42375548c0e)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/d570d273-26e9-42b5-9ba3-170eda1b54c4)|
=> NMA-5249: Make a radio button component

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/SwitchScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsSwitch.kt
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/4421c0b7-811f-4c4c-a772-78aa55a39f3a)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/588e0795-e15a-4870-86b1-26147ea4602c)|
=> NMA-5255: Create switch component

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/ButtonsScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt
| | | |
|-|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/f88be1ef-5477-4dad-8932-c2005fa31b6b)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/dac854a9-cf78-4a02-9de1-0b59309932f3)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/7ba065e3-a81f-44f7-baf3-6e8fba0cfe8b)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/5edf7af6-6a07-46c3-ac4a-1bd556868fa2)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/837ba891-de25-4a39-9798-bfcbcab8a751)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/6a13a1ba-6401-41f6-9153-e4e91b4c8733)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/cf7a9041-2fc1-411c-b7a7-97290a9f7beb)|![image](https://github …
=> NMA-5252: Create SatsIconButton

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/CheckboxScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsTriStateCheckbox.kt
| | | |
|-|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/87fa5740-521c-4e20-86ea-910189d44564)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/f7116d58-d225-480c-a460-d34e6ec73535)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/2a555724-6df6-47f3-a8cc-6d060559c609)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/cc1a53be-7177-4553-b8ee-7522c8819a2c)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/fb33be50-a7cb-468d-a438-f7935476c395)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/8c2e607e-8e9b-449a-ae9c-d28b27a1facf)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/920ff2f0-e3c9-474f-98f8-9e1e8c502831)|![image](https://github …
=> NMA-5258: Add a tri-state checkbox component

sample-app/src/main/kotlin/com/sats/dna/sample/components/CheckboxScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsCheckbox.kt
| | | | |
|-|-|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/3105c19a-47ed-4e4b-9e54-280c23367bd0)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/b855fa5f-6918-4245-a5d9-5000c27e9f91)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/013ce4e8-2645-4ffb-b492-792398bd9788)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/694dd5b9-9219-4362-afdf-c86d1f79b33c)
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/e00d315c-a051-4ce3-b3ec-ba4909342131)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/b015e4ff-5867-47f9-8b3e-f8bef354ad02)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/ee84c636-171b-4b2c-8fbe-b67c44935922)|![image](https://githu …
=> NMA-5250: Build regular checkbox component

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/CircularProgressIndicatorScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsCircularProgressIndicator.kt
| | | | |
|-|-|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/b6e1d62f-51a6-46a1-8f19-e977dfb17b0f)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/3870d558-4ed7-4f35-9e67-48dd07c99e5e)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/918696d9-f099-494f-b7aa-1b3c21ef1971)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/053e2ba0-366f-402f-a575-d3b8e849c41e)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/787b77f6-dad5-4390-9ca0-39a8491728c5)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/a4628a10-c0c1-44a1-8d12-b076e487f03a)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/23924750-0e89-46fd-9c55-07835ff293d7)|![image](https://gith …
=> NMA-5251: Create a circular progress indicator

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/SatsTextFieldScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsOutlinedTextField.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsTextField.kt
| lightmode | darkmode |
| --- | --- |
| ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/2e135942-e0a3-49fd-a56c-94ea00b70ae0) | ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/26f5db58-7169-4d4f-9b49-875383cf9898) |
=> NMA-5272: SatsTextField and SatsOutlinedTextField components

gradle/libs.versions.toml, sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/PlaceholderScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/build.gradle.kts, sats-dna/src/main/kotlin/com/sats/dna/components/Placeholders.kt
| Dark | Light |
| ---- | ----- |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/e3f1531f-68e0-4030-9da0-85f2c904ce04) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/3c4ed699-ac3b-428f-a7e3-134c98f4a04e) |
=> NMA-5422: Build placeholder components

core-tooling/src/main/kotlin/com/sats/dna/tooling/LightDarkPreview.kt, core-tooling/src/main/kotlin/com/sats/dna/tooling/Previews.kt, sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/CompletedWorkoutListItemScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/CompletedWorkoutListItem.kt, sats-dna/src/main/kotlin/com/sats/dna/components/WorkoutTypeIcon.kt, sats-dna/src/main/kotlin/com/sats/dna/shapes/SatsShapes.kt
**New component.** This component displays a list item for the Completed Workouts list. It is similar to what's already in the Member App, but slightly altered to fit the current capabilities of the Completed Workouts list.
| Light | Dark |
| ----- | ---- |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/1ca916c1-aca3-424a-8e1e-9685580dbc3e) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/df7ec5fb-76ad-4cfb-b781-a9cd192c2f84) |
| Small font | Large font |
| ---------- | ---------- |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/4af4003e-8db5-4a86-a3fa-cdcce9e15996) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/ad0dd464-bfec-42a3-824e-fdf047850ea1) |
=> NMA-5420: Build Completed Workout List Item component

sample-app/src/main/AndroidManifest.xml
https://github.com/sats-group/sats-dna-android/assets/386122/9ce27afa-5aec-4955-89a2-b1081cc71288
=> NMA-5417: Support predictive back gestures

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/CompletedWorkoutListItemScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/UpcomingWorkoutListItemScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/CompletedWorkoutListItem.kt, sats-dna/src/main/kotlin/com/sats/dna/components/UpcomingWorkoutListItem.kt, sats-dna/src/main/kotlin/com/sats/dna/components/icons/DefaultInstructorIcon.kt, sats-dna/src/main/kotlin/com/sats/dna/components/icons/WorkoutTypeIcon.kt, sats-dna/src/main/kotlin/com/sats/dna/components/schedule/Schedule.kt
* Made some minor tweaks to the schedule component. Making sure the time of the workout rarely breaks into two lines. 
* Added a component for upcoming workouts.
* Added a default icon component for instructors.
=> NMA 5419: Add component upcoming workouts

gradle/libs.versions.toml, sats-dna/build.gradle.kts, sats-dna/src/main/kotlin/com/sats/dna/components/Placeholders.kt
[The accompanist-placeholder library is deprecated](https://github.com/google/accompanist/pull/1672) and scheduled for removal, in favor of people implementing the feature themselves. So that's what this does.
=> NMA-5423: Fork placeholder modifier from Accompanist

sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
=> NMA-5443: Add snackbar padding to SatsScreen

sample-app/src/main/kotlin/com/sats/dna/sample/components/UpcomingWorkoutListItemScreen.kt
=> NMA-5487: Fix compilation issue in sample app

sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/Schedule.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/UpcomingWorkoutContent.kt
=> NMA-5648: Fix Schedule spacing

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/colors/ColorsScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/LabelsScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorsDark.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorsLight.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsLabel.kt
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/9900e67a-a0e3-43cc-945b-b10f25b1c78d)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/6fe0620c-9c3c-4713-b861-ecc0d222d37f)|
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/6036f108-ef1c-4818-b615-19867fea6d65)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/7e99f08d-fe3e-4ca6-ad19-094263fa91c3)
=> NMA-5655: Create new label components

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/BannerScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsBanner.kt
=> NMA-5660: Create new Banner component

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/TrafficLightsScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/TrafficLightsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/TrafficLight.kt, sats-dna/src/main/kotlin/com/sats/dna/components/TrafficLights.kt
=> NMA-5675: Add Traffic Lights Component

sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/Schedule.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/ScheduledWorkout.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/UpcomingWorkoutContent.kt
* Adds the option to display information about waiting list in a scheduled workout even if the member has a spot.
=> NMA-5686: Add waitinglist text to spot secured

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/GeneralListItemScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/GeneralListItemSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsGeneralListItem.kt
=> NMA-5709: Create SatsGeneralListItem

sample-app/src/main/kotlin/com/sats/dna/sample/components/GeneralListItemScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsGeneralListItem.kt, sats-dna/src/main/res/drawable/ic_arrow_down.xml, sats-dna/src/main/res/drawable/ic_arrow_right.xml
- Making the leading icon optional
- Making it possible to disable
=> NMA-5709: Refactor SatsGeneralListItem

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/ComponentScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/EmptyStateScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/EmptyStateSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt, sats-dna/src/main/kotlin/com/sats/dna/internal/MaterialText.kt
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/cf5fc238-2be2-4f74-a9ab-91bc583f35f3)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/351ebcc0-0286-4a01-8b60-3147c9095b9a)|
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/5e32a455-0fdb-4a3e-976a-88e66ec0bf29)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/a2e9ed9f-db94-4713-92ee-775728b70a68)|
=> Create new SatsEmptyState component

sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt
=> NMA-5949: Fix content colors for SatsEmptyState component

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/YourMostBookedSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/YourMostBookedCard.kt, sats-dna/src/main/kotlin/com/sats/dna/components/internal/GxSessionCard.kt
Building on top of https://github.com/sats-group/sats-dna-android/pull/290.
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/7f06d3c8-ac51-4bc1-a9df-62611f9bb855)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/e493a01c-5c9d-4d73-acbd-01f6f0541373)|
=> NMA-5954: Create Your Most Booked component

sats-dna/src/main/kotlin/com/sats/dna/components/appbar/TopAppBar.kt
Kinda needs https://github.com/sats-group/sats-dna-android/pull/292.
=> NMA-5956: Fix Material 3 Top App Bar colors

sats-dna/src/main/kotlin/com/sats/dna/components/internal/GxSessionCard.kt
| ------ | ----- |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/f4114956-e74d-48ed-bcc9-f002beda33ea) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/bca27b92-739c-475a-8862-2c23a0fb7939) |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/c3c3fb1e-7226-4e98-851d-5eecf107b5e6) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/37cc81d3-45c5-4401-8445-0ce654088b38) |
=> Fix colors in GX Session Card component

sats-dna/src/main/kotlin/com/sats/dna/components/JoinYourFriends.kt, sats-dna/src/main/kotlin/com/sats/dna/components/internal/GxSessionCard.kt
| ------ | ----- |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/e9a2b398-22f2-4002-94fa-d53f4b30e7d4) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/8d2f6a79-3349-4fae-9409-b28a8eb336f9) |
=> NMA-5965: Fix GX Session Card constraints

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ScheduleSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/Schedule.kt
| | |
|-|-|
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/aed4e8c4-0f26-44cd-b3ad-6ff1736a1885) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/4d375ef7-d0f1-49a6-9b72-a34181cc0869) |
=> NMA-6074: Create placeholder component for Schedule

sats-dna/src/main/kotlin/com/sats/dna/components/SatsOutlinedTextField.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsTextField.kt
| | |
|-|-|
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/f27c960d-5f75-4bec-84b5-76ca9767752d) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/62f5d0ee-f123-49c4-af7c-8189217ade6a) |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/19b3fcad-fec4-4234-95e6-bbb7d714412c) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/75ddec4b-28fc-403d-9fb8-9cc5a1e00729) |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/620feb5c-54ad-4d69-a4b4-7aac7e33098c) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/d2c2d819-2430-40be-a8d3-76760c113a15) |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/b62c88a7-546d-4a4b-afdb-9c6dbee4cfa4) | …
=> NMA-6071: Add supporting text support to text fields

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/appbar/TopAppBar.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt
| | |
|-|-|
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/27d4a819-aeb3-48af-911e-ae54e1a599c7) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/321220df-e807-427a-9fb1-9fed0d249650) |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/694ce301-6d8c-45a0-b284-462e05dd8238) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/ba9e79d9-c0b0-46f6-8387-a281ca1f1989) |
=> NMA-6130: Create bell icon button component

sample-app/src/main/kotlin/com/sats/dna/sample/screens/SnackbarSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/snackbar/SatsSnackbar.kt, sats-dna/src/main/kotlin/com/sats/dna/components/snackbar/SatsSnackbarVisuals.kt
=> NMA-6120: Add new snackbar error theme

sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/Schedule.kt
| light mode | dark mode |
| --- | --- |
| ![image](https://github.com/sats-group/member-app-android/assets/107850862/11f98ae1-ed0a-4987-97d5-26599f06783d) | ![image](https://github.com/sats-group/member-app-android/assets/107850862/f235ce93-d1ea-4bab-8e94-82178e5bad6e) |
| ![image](https://github.com/sats-group/member-app-android/assets/107850862/74a5954b-bdd9-4871-b1b4-5c3db01bcb1f) | ![image](https://github.com/sats-group/member-app-android/assets/107850862/7525f1c0-3ec3-4631-b241-a153338e8712) |
=> NMA-6230: Add Card Button to Schedule

sats-dna/src/main/kotlin/com/sats/dna/components/button/CardButton.kt
| before | after |
| --- | --- |
| ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/7722e9cd-8dd8-4d37-84cb-58cab78f4e72) | ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/af621f07-8d2b-4fa3-b545-7c65907b9b35)
=> NMA-6288: Fix vertical alignment and click area

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeBackgroundSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/ChallengeBackground.kt, sats-dna/src/main/res/drawable/challenge_background_top.xml
| Phone | Tablet | Sample
|-|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/4695b68d-895b-4150-8f90-5a25f240bd27)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/a73b6677-4dec-41e4-a2d3-0f38ff71cebc)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/6c9c938f-bd68-4047-aebc-5723cad178a0)|
=> NMA-6301: Create challenge background component

sample-app/src/main/kotlin/com/sats/dna/sample/screens/Colors2SampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors2.kt
Well, it's not used anywhere yet, but whatever.
=> NMA-6414: Change fixed progress bar background to White 40

sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
Forgot about this one in #377.
=> NMA-6416: Add missing protein bar result typealias

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeBackgroundSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/TopAppBarSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/TypographySampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/UpcomingWorkoutListItemSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsBanner.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsSearchBar.kt, sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsLargeTopAppBar.kt, sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsTopAppBar.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton2.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColorProvider.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonIconContent.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonSize.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton2.kt, sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBar.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/SatsUpcomingWorkoutListItem.kt, sats-dna/src/main/kotlin/com/sats/dna/typography/SatsTypography.kt
- **Extract shared functionality between buttons**
- **Implement new Icon Button component**
- **Implement new Button component**
- **Update sample app to use new buttons**
See https://github.com/sats-group/member-app-android/pull/4212 for usages.
=> NMA-6335: Create new button components with proper sizing

sats-dna/src/main/kotlin/com/sats/dna/components/card/ChallengeCard.kt
| Before |    After  |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/9d48c5a8-a8b7-495d-b6d4-5f07fbb74dff)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/7ecffca2-60a7-46e5-af8b-1208cde5f795)|
=> NMA-6302: Use small button for challenge cards

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/TitledSectionSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledSection.kt
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/ad24ae08-d54c-4414-b087-5ce51953b834)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/5bbd21af-82c8-4397-92d3-540b3721f601)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/d6d5eb19-c322-4d3d-928d-13e1bc9c515b)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/8d33643e-69ec-42f1-ae93-8c40516c3823)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/7f0ad884-5fff-4002-bc33-fafc2386bf14)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/5b73f919-5a4d-4382-8c58-de764b8e7588)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/6545706e-0eca-4d4b-aa05-9c8d6eee77ee)|![image](https://github.c …
=> NMA-6421: Create new Titled Section component

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/ArticleCardSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeCardSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsDismissButton.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/ChallengeCard.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsArticleCard.kt
Design: [Figma](https://www.figma.com/file/Nu1V7557V7KovgpZCNDObQ/%F0%9F%93%B1-sats-app-components-new?type=design&node-id=4129-13504&mode=design&t=SsTM20S1x3Z0OM8p-0)
|  |  |
| --- | --- |
| ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/eaab77f4-3d6a-4ac2-b1e9-99c7e7b51070) | ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/2f5f6237-042d-4f04-b225-eeb1ab2a01f2) |
| ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/de13f43f-3f09-4385-bdad-1a67c78d127d) | ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/fe0d44db-6f3b-40ea-9733-80ff74e611c7) |
=> NMA-6462: Campaign Module -> new Article Card component

sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/bd5ece36-f9b2-4736-9698-4f4fe2564e04)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/24e9db69-ea7e-4efa-8442-ebe42a6cd754)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/9d4699d6-c162-4f36-8ec0-632ecf0c490a)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/79aff956-17fb-4e93-b9c0-b4d9935a9daf)|
=> NMA-6475: Add scroll connection to sample screen top app bar

scripts/move-icons-to-dna.js
Move the stuff from https://github.com/sats-group/sats-dna-android/pull/406 and https://github.com/sats-group/sats-dna-android/pull/407 over to :sats-dna.
=> NMA-6500: Move generated files to :sats-dna

sats-dna/build.gradle.kts
https://medium.com/androiddevelopers/jetpack-compose-strong-skipping-mode-explained-cbdb2aa4b900
=> NMA-6515: Enable Compose strong skipping

sats-dna/src/main/kotlin/com/sats/dna/components/sessiondetails/SatsFriendsBookingStatusListItem.kt
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/a4a9f699-6efd-4949-ad6a-45858775e7ce)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/c1461afc-73f9-4bfb-99d5-c324ebcc113c)|
=> NMA-6537: Fix issue with long names in invitee list items

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt
| | |
|-|-|
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/66e2eb5c-4d33-4335-a3aa-365b5c5d051d) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/e84badf8-7036-4306-bf1c-682aad7f111c) |
=> NMA-6544: Bring back the CTA button

sats-dna/src/main/kotlin/com/sats/dna/components/progressbar/SatsCircularSteppedProgressIndicator.kt
As per the design: [Figma](https://www.figma.com/file/Nu1V7557V7KovgpZCNDObQ/%F0%9F%93%B1-sats-app-components-new?type=design&node-id=3613-19640&mode=design&t=TTDjF1NIjnGxCMWf-0)
=> NMA-6304: Update circular progress indicator color

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ArticleCardSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeCardSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsDismissButton.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsDismissButtonContent.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsArticleCard.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsChallengeCard.kt
* Adds loading to the SatsChallengeCard states for when you're joining or dismissing a challenge.
* Makes the SatsDismissButton handle disabling itself when loading.
=> NMA-6584: Add loading states to action buttons in SatsChallengeCard

gradle/libs.versions.toml, sample-app/src/main/kotlin/com/sats/dna/sample/screens/FormInputFieldsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsFormInputFields.kt
- Use alpha releases of Compose
- Use new text APIs
=> NMA-6589: Bump Compose to version 1.7.0-alpha06

sample-app/build.gradle.kts, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt
- **Put home screen list items into sections**
- **Implement simple search search for items**
=> NMA-6601: Some sample app home screen stuff

sample-app/src/main/kotlin/com/sats/dna/sample/screens/CheckboxSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/ColorsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorPrimitives.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsCheckbox.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsRadioButton.kt
Update colors to match current design system.
=> NMA-6629: Update colors to match design system

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ColorsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors.kt
- **Use outlines where intended**
- **Rewrite colors sample screen**
=> NMA-6638: Rewrite colors sample screen

sample-app/src/main/kotlin/com/sats/dna/sample/screens/FancyTopAppBarSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsFancyTopAppBar.kt
Fixes https://hfnswedenab.atlassian.net/browse/NMA-6682. I think.
=> NMA-6682: Ensure fancy top app bar expanded between 0f..1f

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeBackgroundSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsTopAppBar.kt
Make it possible to add custom colors to the SatsTopAppBar component 🎨🖌️
=> NMA-6693: Add colors to SatsTopAppBar

sats-dna/src/main/kotlin/com/sats/dna/components/SatsFormInputFields.kt
JIRA: https://hfnswedenab.atlassian.net/browse/NMA-6675
=> NMA-6675: Add datetime and text field placeholders

sample-app/src/main/kotlin/com/sats/dna/sample/MainActivity.kt, sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/internal/SharedTransitions.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt
https://github.com/sats-group/sats-dna-android/assets/386122/a45f5adb-a8a3-4e4a-9b88-6fc768fb8214
=> NMA-6667: Fade top app bars between screens

sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsArticleCard.kt
Did the following changes:
1. Add isFixed as parameter to determine text and background color
2. Make the image fill the entire card size
3. Make the height constant at 234.dp
4. Set maxLines 2 for the title
5. Set maxLines 3 for the description
6. Make article title optional
https://hfnswedenab.atlassian.net/browse/NMA-6719
=> NMA-6719: Update article card to support news

sample-app/src/main/kotlin/com/sats/dna/sample/screens/styles/ColorsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt
- Update Surface Fixed Featured FG colors
- Add fixed divider color
=> NMA-6751: Update colors from color system

sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsArticleCard.kt
JIRA: https://hfnswedenab.atlassian.net/browse/NMA-6776
=> NMA-6776: Add article card placeholders

sats-dna/src/main/kotlin/com/sats/dna/components/SatsChoiceBox.kt
* The color for unselected fixed was wrong, now it isn't 😎
=> Fix wrong unselected description color in SatsChoiceBox

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/routes/styles/ColorPrimitivesSampleScreenRoute.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/SampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/styles/ColorPrimitivesSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorPrimitives.kt
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/95c0637d-9b93-459d-b56f-8d3709c70057)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/6577215d-9439-4b6e-a6cb-b632b58403c8)|
=> NMA-6847: Showcase color primitives in sample app
