sats-group/sats-dna-android

sample-app/src/main/kotlin/com/sats/dna/sample/colors/ColorsScreen.kt
Essentially a copy of the screen from the implementation over at the member app repo, but with some clean-up.
|   |   |
| - | - |
| ![image](https://user-images.githubusercontent.com/386122/226392698-df86851b-a421-4c3a-8372-5fad2fbe929e.png) | ![image](https://user-images.githubusercontent.com/386122/226392705-386e08ac-ca8c-4ba2-b766-5b22a5cc6d15.png) |
=> NMA-4941: Sample App – Colors

gradle/wrapper/gradle-wrapper.properties
Release logs: https://docs.gradle.org/8.1-rc-1/release-notes.html
=> NMA-4943: Update to Gradle 8.1-rc-1

sample-app/src/main/kotlin/com/sats/dna/sample/colors/ColorsScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorsDark.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorsLight.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorsPreview.kt
Made new `waitingList` and `onWaitingList` colors, so we don't break existing usages of `waitList` and `onWaitList`, and because the names are better. :sunglasses: 
We need this for waiting list buttons later. I've also deprecated `waitList` and `onWaitlist` in favor of the new colors.
See the [color specs in Figma](https://www.figma.com/file/WzKCwRY09zn4rzRVfY0YvdRt/sats-ds-styles?node-id=1-2&t=fNnPqOrIAoaLKViD-0) for reference.
|   |   |
| - | - |
| ![image](https://user-images.githubusercontent.com/386122/226632833-15052c75-b699-4f6c-b51a-584db2f20a23.png) | ![image](https://user-images.githubusercontent.com/386122/226632845-aa478821-369e-4188-9f97-1b6cf0fc1a7e.png) |
=> NMA-4944: Add disabled waiting list colors

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/buttons/ButtonsScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/previews/CleanButtonPreviews.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/previews/CtaButtonPreviews.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/previews/PrimaryButtonPreviews.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/previews/SecondaryButtonPreviews.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/previews/WaitingListButtonPreviews.kt, sats-dna/src/main/kotlin/com/sats/dna/shapes/SatsShapes.kt, sats-dna/src/main/kotlin/com/sats/dna/spacing/SatsSpacing.kt
Create new `SatsButton` component. A button has a required `onClick` and `label` parameter, and some other optional parameters that further customize its looks. These parameters control
- if button is in a loading state,
- if it's enabled, and
- if it's of the large variant.
Icons are not supported at this time, but adding them shouldn't be too difficult.
**Some screenshots from the Sample App:**
|   |   |
| - | - |
| ![image](https://user-images.githubusercontent.com/386122/226965845-831a9f40-82b3-4fc5-9a57-d82912826b29.png) | ![image](https://user-images.githubusercontent.com/386122/226965874-8bce0603-dcff-49ea-b77f-7f0623c8d082.png) |
It's worth noting that there's [an ongoing discussion about the Clean Disabled style](https://www.figma.com/file/Nu1V7557V7KovgpZCNDObQ?node-id=3:1183#399 …
=> NMA-4945: Create Sats Button Component

.github/workflows/release.yml
I've added the SERVICE_ACCOUNT_JSON secret to the repo (found in the key vault).
=> NMA-4952: Pass service-account JSON to upload action

gradle/libs.versions.toml
The idea is that, if the compiler is listed as a library, then Renovate will actually check it. Remains to be seen if it works, though!
=> NMA-5013: Help Renovate update the Compose Compiler

sample-app/src/main/kotlin/com/sats/dna/sample/icons/IconsScreen.kt
The control panel allows showing borders around the icons, which makes it easier to see what part of the icon is just padding.
The control panel also lets you control whether to view the icons in their default size (24 × 24 px), or in a larger 48 × 48 px.
| | |
|-|-|
| ![image](https://user-images.githubusercontent.com/386122/232525364-f02449f6-a057-437c-95c9-66253a2dafd8.png) | ![image](https://user-images.githubusercontent.com/386122/232525377-7a822d65-d9fc-49ee-b33b-b9097864b9e7.png) |
| ![image](https://user-images.githubusercontent.com/386122/232525521-1654209a-3529-456e-a8eb-7f96ed11f8ac.png) | ![image](https://user-images.githubusercontent.com/386122/232525534-853aa4d3-095e-41a1-a52a-9bdb4081f2b0.png) |
=> NMA-5030: Add control panel to sample app icons screen

sats-dna/src/main/kotlin/com/sats/dna/components/SatsSurface.kt
Mostly just a proxy to Material's `Surface`, but with a smaller API surface, and ready for Material 3.
=> NMA-5254: Create a SatsSurface

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/SnackbarScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsSnackbar.kt, sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt
A drop-in replacement for the default Material snackbar, following [the Figma designs](https://www.figma.com/file/Nu1V7557V7KovgpZCNDObQ/sats-app-components-new-(wip)?type=design&node-id=1698-12618&mode=dev).
| | |
|-|-|
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/e9678990-e471-4dfc-abb1-5dcefddda174) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/e651ae1f-a0c9-40f1-8df6-7cb88d1e8cdc) |
The main difference is probably that we're using a transparent `SatsButton` for the action, and that has an `action` color. I think that kind of makes sense, though, but feedback's more than welcome. This implementation also doesn't support a title, mostly because we never really have a title available to us. iOS shows titles such as “400 Bad Request”, …
=> NMA-5377: Introduce new SatsSnackbar component

gradle/libs.versions.toml, sample-app/build.gradle.kts, sample-app/src/main/kotlin/com/sats/dna/sample/MainActivity.kt, sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsIconButton.kt, settings.gradle.kts
Update compose to 1.5.0-beta03 and replace accompanist animated navigation with jetpack compose navigation that now has built in animations. Also updated accompanist to 0.31.5-beta that supports the new jetpack compose version.
=> Replace accompanist navigation with jetpack compose navigation

sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt
As data objects are now stable in Kotlin 1.9.0, it's recommended that all sealed sub-objects are declared as such. There's even a lint warning for this now with a quick-fix, which is what I've applied here.
https://kotlinlang.org/docs/whatsnew19.html#stable-data-objects-for-symmetry-with-data-classes
=> NMA-5430: Convert sealed sub-objects to data objects

sample-app/src/main/kotlin/com/sats/dna/sample/components/UpcomingWorkoutListItemScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/UpcomingWorkoutListItem.kt
This component is used not only for the current user's own upcoming
workouts, but also for their friends' upcoming workouts. That means that
it would need to be possible to also join (book) friends' workouts from
the list item, and not just unbook their own.
=> NMA-5455: Allow any kind of button in upcoming workout item

gradle/libs.versions.toml, sample-app/build.gradle.kts, sample-app/src/main/kotlin/com/sats/dna/sample/MainActivity.kt, sample-app/src/main/res/values/themes.xml, sats-dna/build.gradle.kts, sats-dna/src/main/kotlin/com/sats/dna/theme/SatsTheme.kt
Since accompanist-systemuicontroller is deprecated now, let's move on to
greener pastures.
We're gonna need to update the Member App, too, after merging this.
=> NMA-5518: Use new APIs fro edge-to-edge

.github/workflows/release.yml
Specifically, split up building artifacts and releasing them. This will
allow us to monitor them individually, and also retry release jobs if
they fail, without having to rebuild.
=> NMA-5637: Split release.yml into more jobs

.github/workflows/release.yml
- Match file path for uploading to the Play Store.
- Checkout code before publishing library, so that `./gradlew` is available.
=> NMA-5637: Checkout code before publishing

.github/workflows/release.yml
- Set VERSION_NAME for releasing
- Give sample-app-release.aab a unique artifact name
=> NMA-5637: More release pipeline fixes

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/ChipsScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/chip/ChipsScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsChip.kt
As per https://www.figma.com/file/Nu1V7557V7KovgpZCNDObQ/sats-app-components-new-(wip)?type=design&node-id=17-14063&mode=design&t=LhVzelHJvgMAcQre-0. However, there is no Disabled state for filter chips in the design yet, so I YOLO'd it.
https://github.com/sats-group/sats-dna-android/assets/386122/8005ec59-8bd6-465f-85d3-2db135dd580d
=> NMA-5653: Create new Chip components

sample-app/src/main/kotlin/com/sats/dna/sample/components/LabelsScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsLabel.kt
This should always show the untranslatable “blue”, “silver”, “gold” or
“platinum” texts, depending on which level it represents.
=> NMA-5688: Remove text property from SatsRewardsLabel

sample-app/src/main/kotlin/com/sats/dna/sample/components/CampaignModulesScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsCampaignModule.kt
Apparently, they're not always there, as is the case for one of our new campaigns.
|Before|After|
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/a3442a33-5271-42f2-b7c2-bf6713594154)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/30d81309-27ca-436a-accf-c40206a5c7c3)|
=> NMA-5698: Make subtitle optional in Campaign Module

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/TagsScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/LabelsSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/TagsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsTag.kt
This has been renamed in the design system, as iOS was unable to use the name “Label”. I've kept the old names for backwards compatibility reasons.
- Rename SatsLabel → SatsTag
- Rename SatsLabelColor → SatsTagColor
- Rename SatsRewardsLabel → SatsRewardsTag
=> NMA-5749: Rename SatsLabel → SatsTag

sample-app/src/main/kotlin/com/sats/dna/sample/components/card/SatsCardScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsCampaignModule.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsCard.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/Schedule.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/UpcomingWorkoutContent.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/UpcomingWorkoutListItem.kt
Add a `useMaterial3` flag to `SatsCard`, which will then proxy to an `ElevatedCard` instead of the old Material 2 `Card` component. Users of Material 3 cards must be careful to also use text and icon components from Material 3, so that styles are applied correctly.
Note that Material 3 elevated cards have a slightly different surface tint than Material 2's cards, causing a little bit of an inconsistency. See the images 
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/2c7a2ad4-8c8f-4a98-9f1f-bd24d0bec4b5)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/f75fa048-f4da-4a6c-8232-10ca862e6c22)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/7ef8e9e4-7bc2-437d-9349-ed6fa098db2c)|![image](https://github.com/sats-grou …
=> NMA-5755: Support Material 3 elevated cards in SatsCard

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/components/BrandLogoScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/BrandLogoSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/BrandLogo.kt, sats-dna/src/main/kotlin/com/sats/dna/internal/MaterialIcon.kt
A new component that, given a brand (`Sats` or `Elixia`) paints the correct logo.
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/84b844bc-e77d-4668-8d6d-c98c2e8855ae)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/14f62bd3-da17-4484-9770-8e251440b263)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/034aab58-cdca-4ec8-90ac-c569f1c8e820)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/44622256-0448-43d3-8af3-31c9b372ba40)
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/edae7c47-8e26-4a20-bb04-51407e469d07)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/ebc0d233-073e-452f-982e-35890a54d1a3)| …
=> NMA-5770: Introduce a BrandLogo component

sample-app/src/main/kotlin/com/sats/dna/sample/components/card/SatsCardScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/BrandLogo.kt, sats-dna/src/main/kotlin/com/sats/dna/components/CompletedWorkoutListItem.kt, sats-dna/src/main/kotlin/com/sats/dna/components/LocalUseMaterial3.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsBanner.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsCampaignModule.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsChip.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsGeneralListItem.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsSurface.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/LikeButton.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsCard.kt, sats-dna/src/main/kotlin/com/sats/dna/components/screen/SatsScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/Schedule.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/UpcomingWorkoutContent.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/UpcomingWorkoutListItem.kt, sats-dna/src/main/kotlin/com/sats/dna/internal/MaterialIcon.kt, sats-dna/src/main/kotlin/com/sats/dna/internal/MaterialText.kt
This lets us not have to pass `useMaterial3` around all over the place.
Instead, we set it on the top (screen) level, and then it defaults to
whichever screen was set further down the line.
Before, we had to do something like this:
```kt
M3SatsScreen {
SatsSurface(useMaterial3 = true) {
SatsBanner("Banner text", useMaterial3 = true)
}
}
```
Now, it should be enough just to use an `M3SatsScreen`, and the
components will respect the Composition Local:
```kt
M3SatsScreen {
SatsSurface {
SatsBanner("Banner text")
}
}
```
In fact, I've removed the `useMaterial3: Boolean` parameter from all components except for `SatsSurface`. The only way to explicitly change this now is through `LocalUseMaterial3`. This avoids ambiguity and simplifies an otherwise complex API surface.
The reason for keeping …
=> NMA-5787: Put Material 3 usage in a CompositionLocal

sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColorsDark.kt
The previous color was not compliant with the On Rewards color.
=> NMA-5788: Update dark mode color for Rewards Blue

sats-dna/src/main/kotlin/com/sats/dna/tooling/PreviewAnnotations.kt
There's really no reason for these to be internal to the library.
=> NMA-5794: Expose preview annotations

.github/workflows/release.yml
Now that one of our fonts is moved to a privately published package in the SATS-group. We need to add GitHub credentials when building our release versions.
=> Add github credentails to the necessary steps in the release workflow.

.github/workflows/release.yml
- Removes play store credentials from the build library task.
@sindrenm Looking through the release workflow it's seems like a slip up to me that we add Play Store credentials when building the library. But obviously correct me if I'm wrong 🙏😅
=> Remove unnecessary play store credentials when building only the library

sample-app/src/main/kotlin/com/sats/dna/sample/screens/SessionDetailsInfoLabelSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/sessiondetails/SessionDetailsInfoLabel.kt
Add a `SessionDetailsInfoLabelPlaceholder` that can be used instead of a `SessionDetailsInfoLabel` to signal that content is loading. To make sure that this takes up as much space as the non-placeholder variant, the non-placeholder variant now doesn't change height depending on whether it's clickable or not. That means that there is now more padding between items that are non-clickable, which might not be exactly what I want.
I've also added Material 3 support by using `MaterialText` and `MaterialIcon` internally, which chooses the correct one based on `LocalUseMaterial3.current`.
|   |   |
| - | - |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/3b83e1a4-57e8-42ee-8ecf-512540bab832) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/5c5fb531-a …
=> NMA-5907: Create placeholders for info labels

sample-app/src/main/kotlin/com/sats/dna/sample/screens/EmptyStateSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt
This changes `SatsEmptyState` to no longer be wrapped in a `SatsCard` by default, but rather have no background color. Its layout is still exactly the same. A new `SatsEmptyStateCard` is introduced that replicates the behaviour from before.
=> NMA-5945: Default SatsEmptyState to no background

sats-dna/src/main/res/drawable/ic_elixia.xml
I tried replacing the `BrandLogo` composable to use just a `Text()` instead with the correct font. However, it seems the letter spacing is a little different for the SATS and Elixia logos, and there's also the issue with line heights not being too easy to tweak.
=> NMA-5998: Ignore too-large-vector warning

sats-dna/src/main/kotlin/com/sats/dna/components/SatsBanner.kt
=> NMA-6012: Fix default content color for SatsBanner in dark mode

sats-dna/src/main/kotlin/com/sats/dna/components/SatsBanner.kt
The banner should always use the same colors, as per the Design System. Thus, it doesn't make sense to allow that as part of the API surface.
Similarly, the optional action should always be represented by a Clean Button, so allowing a slot for the button is also senseless. Thus, a new `SatsBannerAction` has been introduced in its stead.
=> NMA-6014: Restrict the SatsBanner API surface

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/BrandLogoSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/CompletedWorkoutListItemSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/DividersSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/SessionDetailsInfoLabelSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/SwitchSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/TypographySampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/UpcomingWorkoutListItemSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/CompletedWorkoutListItem.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsDivider.kt
They're impossible to see on a surface color, but they adhere to the spec.
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/ad04b30a-cfb3-40c8-a38c-429b67ea094c)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/99efc3fc-b282-43e4-89fa-292ce3eb36c4)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/7bf01900-83ea-426d-9b7f-9c42137cbf30)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/df3719b5-a9f7-424e-9e6e-759524aa376e)|
| | |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/8fb9a298-2322-4f2b-9f01-4ca2686ae30b)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/08b6effc-1315-42ea-bb4b-dc29a2fdfdff)| …
=> NMA-6039: Create Divider components

sample-app/src/main/kotlin/com/sats/dna/sample/screens/CardSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsCard.kt
Create `SatsCard` from scratch using only a `SatsSurface` with some elevation. This fixes a color issue with the Material 3 (`ElevactedCard`-backed) cards, where a tonal elevation was applied automatically, and also just aligns Material 2 and Material 3 cards to look exactly the same.
| | |
|-|-|
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/b56f0015-4b96-4d3a-9095-107e9b3610a0) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/6799bb0c-3870-48c6-b00d-338d2f8fddd7) |
=> NMA-6069: Fix colors for `SatsCard` when in Material 3

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt, sats-dna/src/main/kotlin/com/sats/dna/tooling/PreviewAnnotations.kt
=> NMA-6073: Fix button clipping on large font scales

sample-app/src/main/kotlin/com/sats/dna/sample/screens/SnackbarSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/TypographySampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/snackbar/SatsSnackbar.kt, sats-dna/src/main/kotlin/com/sats/dna/components/snackbar/SatsSnackbarVisuals.kt, sats-dna/src/main/kotlin/com/sats/dna/typography/SatsTypography.kt
- Make title bold
- Add some spacing between title and message
- Move snackbar dismiss action to top right corner
- Always put leading icons to the top left
- Make leading icons required
- Span full width for title, message and dismiss action
- Move regular action underneath the message, aligned to the right
What's your opinion on this? It looks a little wonky with the icons in grandma mode (due to their size not changing alongside the font scale), but other than that, I feel like this makes some sense.
=> NMA-6119: Make some opinionated changes to the snackbar

sample-app/src/main/kotlin/com/sats/dna/sample/screens/Colors2SampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors2.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors2.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsOutlinedTextField.kt
|-|-|
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/3df53c2f-da9c-4d76-972b-66f2ebe2049f) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/25fc9ebe-4b51-4b95-8a96-f442fbe873ed) |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/a6ab9c80-e184-40eb-84ed-c0e9be008b17) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/7a5a92ad-6856-458f-ad3c-f71433ee3feb) |
=> NMA-6142: Add new border colors to outlined text fields

sample-app/src/main/kotlin/com/sats/dna/sample/screens/Colors2SampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors2.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors2.kt
=> NMA-6189: Add new On Surface Featured color

sats-dna/src/main/kotlin/com/sats/dna/components/SatsEmptyState.kt
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/fe697a17-a7c7-4ae5-a15a-c2ed60457a31)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/37583141-16f6-40de-99ce-c4453b7bce65)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/d168d6e1-7460-423f-9c52-d5dfa9d9cf59)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/d42a80f4-e8f3-41d2-a12e-e2af7aa8ce66)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/91037b95-c1c5-4473-8181-96559e8c8575)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/63faa569-4420-4c60-9c78-975985f62bde)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/e24e325a-3a74-4d48-9f2b-86161a7acdf6)|![image]( …
=> NMA-6247: Increase icon size for empty state component

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/UpcomingWorkoutListItemSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsTitledCard.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonColor.kt, sats-dna/src/main/kotlin/com/sats/dna/components/proteinbar/SatsProteinBar.kt, sats-dna/src/main/kotlin/com/sats/dna/components/upcomingworkouts/UpcomingWorkoutListItem.kt
The Transparent button color was actually colored like Action, so it's been renamed to Action. And then we just removed the old Action color, as that was using the wrong (blue) color of links.
=> NMA-6316: Remove Transparent button color and change Action

sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/cdcf80b7-6c42-4124-812d-92354e40ec7d)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/fec17a4c-fc56-4724-bcaf-9a32475eea33)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/4cd7ded5-892c-499d-8b97-7cfe5a893b5b)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/8bd3b22e-9341-477d-9acf-7cde4a9368c1)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/a0244277-7edb-4c47-a2db-c92a5405c7d6)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/6c657652-85a1-47df-a04e-5bbe6d4139a7)|
=> NMA-6418: Put clean button previews behind fixed backgrounds

sats-dna/src/main/kotlin/com/sats/dna/components/SatsChip.kt
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/e5e53551-fa8a-401a-9aac-3375c5bed5d0)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/5b4ce312-137c-4496-b00e-0f575b4b1b05)|
=> NMA-6417: Fix border color of unselected chips

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/home/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeCardSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/TagsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/GreyScaleModifier.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsChallengeBackground.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsTag.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/ChallengeCard.kt, sats-dna/src/main/kotlin/com/sats/dna/components/progressbar/SatsLinearProgressBar.kt
**New Challenge Cards and updated Tags which are used within the cards 🎴** 
Cards: [Figma design](https://www.figma.com/file/F1I7j15pqrCOkB55ypUqtx/Activity?type=design&node-id=27660-26668&mode=design&t=C0JWiG5xI6k7ymvg-0)
Also updated the thickness of progress bars as per the design system 📏 
| dark mode | light mode |
| --- | --- |
| ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/08712aa2-988c-4de2-900d-26337c8b4cc5) | ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/222918fa-2c03-40fa-8574-f92e880e3580) |
| ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/4b444f01-cfed-4b49-9e7e-0f57a58b8171) | ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/6d03ae22-b554-454e-a36c-b1484446c5dc) |
=> NMA-6302: New Challenge Card + updated Tags

sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsLargeTopAppBar.kt, sats-dna/src/main/kotlin/com/sats/dna/components/appbar/SatsTopAppBar.kt
This would allow us to go from
| this |  to this |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/67b12f22-fa0c-42e0-93db-ce4b84e08e85)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/857a08b7-e462-4e55-80ee-14bfe871b4cc)|
and
| this |  to this |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/1f9d23f5-3bf9-4fdf-9f4c-564b1e9384df)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/90c136eb-717f-4ecb-8552-ec1b846eec23)|
=> NMA-6452: Expose top app bar container color

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ButtonsSampleScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeCardSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButton.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsButtonAnimation.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsDismissButton.kt, sats-dna/src/main/kotlin/com/sats/dna/components/button/SatsDismissButtonContent.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/ChallengeCard.kt
**Created new SatsDismissButton to be used in the disabled version of the new Challenge Card, but also new shit 💩** 
Design: [Figma](https://www.figma.com/file/Nu1V7557V7KovgpZCNDObQ/%F0%9F%93%B1-sats-app-components-new?type=design&node-id=4129-14318&mode=design&t=qz2m3VQuS7An3vDP-4)
| close | dismiss |
| --- | --- |
| ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/5e5d1b71-7b45-49dd-9d9b-4f5a84927fea) | ![image](https://github.com/sats-group/sats-dna-android/assets/107850862/b2fbaabe-35c0-482a-b30c-435d962ca0e2) |
=> NMA-6460: Create and use dismiss button in Disabled Challenge Card

sample-app/build.gradle.kts, sample-app/src/main/kotlin/com/sats/dna/sample/screens/FancyTopAppBarSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsFancyTopAppBar.kt
**Builds upon https://github.com/sats-group/sats-dna-android/pull/389.**
Realized we might need to do this in order to support stuff like the Club Details image gallery and the New Release tags and stuff.
=> NMA-6439: Add slot for image in fancy top app bar

sample-app/src/main/kotlin/com/sats/dna/sample/screens/GeneralListItemSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsCircularProgressIndicator.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsGeneralListItem.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsSearchBar.kt
Ref [this discussion in Figma](https://www.figma.com/file/Nu1V7557V7KovgpZCNDObQ?node-id=1985:3873&mode=design#733684478) the general list items do not need to have a set surface background and should instead inherit their parents background color. 
I checked all places where this is already used, and in all usages the list items were already wrapped in a SatsCard so this shouldn't really break anything in the app. But please double check 🙈
=> NMA-6422: Remove SatsSurface from General List Item

sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors2.kt
This was wrong before. It's right now.
=> NMA-6476: Set correct signal surface bg in dark mode

sats-dna/src/main/kotlin/com/sats/dna/components/SatsPlaceholders.kt
This is closer to our actual text line heights.
| Before |         After        |
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/8fe5ff7f-f521-4237-84bf-0efe0fd7a156)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/ecbb0b0e-a31f-4f83-9cff-c6ddbaa23382)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/fab38f6b-66fa-4ab2-ae90-52ffbb3ad735)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/c2558cb5-c291-4f4a-a115-25b42eb55430)|
=> NMA-6473: Reduce line heights for placeholder paragraph

scripts/.gitignore, scripts/convert-svg-files-to-vector-drawables.js, scripts/package-lock.json, scripts/package.json
Converts all SVGs downloaded from https://github.com/sats-group/sats-dna-android/pull/405 to Android Vector Drawables, so that they can be read natively on Android.
=> NMA-6500: Generate Android Vector Drawables from SVGs

scripts/.gitignore, scripts/generate-sats-icons-from-vector-drawables.js
Given that https://github.com/sats-group/sats-dna-android/pull/406, generate a `SatsIcons.kt` file with references to all the icons.
=> NMA-6500: Generate SatsIcons.kt from vector drawable files

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ChallengeCardSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsChallengeCard.kt
* Adds Sats prefix to ChallengeCard component.
* Add horizontal padding to subtitle so it doesn't touch edges when long
* Add small rounded corner shape to challenge card. 
**Before**: 
**After:**
=> NMA-6509: Fix shape and padding in challenge card. And prefix it with sats

sats-dna/src/main/kotlin/com/sats/dna/components/SatsChallengeBackground.kt, sats-dna/src/main/kotlin/com/sats/dna/components/card/SatsChallengeCard.kt
When using the SatsChallengeCard, without setting both an explicit height and width the card would size itself to the size of the image svg. This PR fixes that so that the challenge background will just size itself to whatever the content size is.
Also removed an unused modifier parameter from the state objects and renamed the dismiss callback to be inline with the other callbacks.
=> NMA-6568: Tweak challenge background so it doesn't have a size of it's own

gradle/libs.versions.toml
This introduces predictive back handling by default.
=> NMA-6634: Use new alpha release of androidx.navigation

gradle/libs.versions.toml
There was a bug introduced in alpha07, which causes a decent amount of crashes in production for us when animating floats. It's been fixed in alpha08, but it's probably better to just downgrade for now and make a hotfix.
=> NMA-6684: Downgrade Compose to 1.7.0-alpha06

sats-dna/src/main/kotlin/com/sats/dna/components/SatsProfileAvatarImage.kt
* The profile avatar image fallback had some wonky colors (was completely white in dark mode which looked quite intense) now they don't 🙏
=> NMA-6683: Fix color of profile avatar image fallback

sample-app/src/main/kotlin/com/sats/dna/sample/screens/ProgressBarsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/progressbar/SatsCircularSteppedProgressIndicator.kt
* Adds a isFailed flag to the stepping progress indicators, so that we can display progress for a failed challenge.
=> NMA-6674: Add isFailed as an option to stepping progress indicator.

sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt
| - | - |
| ![image](https://github.com/sats-group/sats-dna-android/assets/386122/cefa2912-12b3-40cd-b3dd-e6a6c6ef8167) | ![image](https://github.com/sats-group/sats-dna-android/assets/386122/60450f7f-55dd-4d4e-b899-965524248274) |
=> NMA-6705: Fix content color for primary disabled button

sample-app/src/main/kotlin/com/sats/dna/sample/screens/styles/ColorsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsColors.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsDarkColors.kt, sats-dna/src/main/kotlin/com/sats/dna/colors/SatsLightColors.kt
- **Specify fixed/clean colors directly in SatsColors**
These colors should, by design, always be the same in light and dark mode, so settings them in the light and dark color implementations of `SatsColors` just adds more possibilities of making mistakes. Instead,
setting them directly in `SatsColors` means they'll always be the same.
- **Show correct background behind colors in sample**
Fixed content colors and clean buttons should always be on top of fixed backgrounds/surfaces, so that should be how they're represented in the sample app, as well.
- **Change on fixed disabled colors to match DS**
Two color changes to ensure a11y compliance (AA).
=> NMA-6714: Some color changes and fixes

sats-dna/build.gradle.kts
This feature is no longer experimental, so the flag changed.
=> NMA-6741: Use non-experimental strong skipping flag

sample-app/src/main/kotlin/com/sats/dna/sample/screens/components/RadioButtonsSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsRadioButton.kt
* Add fixed color variant of the radio buttons as per the [design system](https://www.figma.com/design/Nu1V7557V7KovgpZCNDObQ/%F0%9F%93%B1-sats-app-components?node-id=4990-2610&t=YSySFsrE8HE9ZaUi-4)
**Screenshot**
=> NMA-6806: Add Fixed color variant to SatsRadioButtons

sample-app/src/main/kotlin/com/sats/dna/sample/MainNavigation.kt, sample-app/src/main/kotlin/com/sats/dna/sample/routes/components/ChoiceBoxSampleScreenRoute.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/HomeScreen.kt, sample-app/src/main/kotlin/com/sats/dna/sample/screens/components/ChoiceBoxSampleScreen.kt, sats-dna/src/main/kotlin/com/sats/dna/components/SatsChoiceBox.kt
* Create a SatsChoiceBox component from the design system [here](https://www.figma.com/design/Nu1V7557V7KovgpZCNDObQ/%F0%9F%93%B1-sats-app-components?node-id=4475-6511&t=YSySFsrE8HE9ZaUi-4) 
**Screenshots:**
| Type | Light  | Dark | Fixed |
| ----------- | ----------- | ----------- | ----------- |
| Checkbox |  ![Screenshot_20240607_112539](https://github.com/sats-group/sats-dna-android/assets/48335680/97000ec0-56c7-49e4-9c80-1f1eb4aa863b)  | ![Screenshot_20240607_112559](https://github.com/sats-group/sats-dna-android/assets/48335680/9ac8007f-d982-47c4-adb1-684be91bac7d) | ![Screenshot_20240607_112544](https://github.com/sats-group/sats-dna-android/assets/48335680/7b562ef8-b0b6-4f28-8d94-5cd166f0a386) |
| Radio | ![Screenshot_20240607_112532](https://github.com/sats-group/sats-dna-android/ …
=> NMA-6798: Create SatsChoiceBox component

sats-dna/src/main/kotlin/com/sats/dna/components/SatsChoiceBox.kt
Prevented the button from being pushed out to the side if the text somehow gets long enough that it doesn't fit
Before and after:
=> Prevent SatsChoiceBox button from clipping if text is long

sats-dna/src/main/kotlin/com/sats/dna/components/SatsFancyTopAppBar.kt
In challenge details we're gonna tweak the header a bit so we need a version that's a bit more flexible than the previous one. Created a header that will transition between collapsed and expanded content of any kind.
https://github.com/sats-group/sats-dna-android/assets/48335680/7dc38e0b-e6d5-4f6c-a8c0-7389f9c4403e
=> NMA-6755: Create a more customisable SatsFancyTopAppBar

sats-dna/src/main/kotlin/com/sats/dna/components/SatsAnimatedCheckmark.kt
|-|-|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/b9fbba09-67c7-47e2-8760-0954f30275f3)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/cf279979-73eb-4d3d-af4b-bcdadf26cdc7)|
|![image](https://github.com/sats-group/sats-dna-android/assets/386122/ff7e1746-0120-4e50-abea-e74e733d33eb)|![image](https://github.com/sats-group/sats-dna-android/assets/386122/7bb49aff-5298-4d9d-88d7-957411beeef2)|
=> NMA-6876: Show completed animated check-mark if in preview
